- name: install docker-compose
  become: yes
  become_user: root
  become_method: sudo
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/1.27.1/docker-compose-$(uname -s)-$(uname -m)" \
      -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
