version: '3.7'

services:
  haporxy:
    container_name: haproxy
    image: haproxy:latest
    command: tail -f /dev/null
    volumes: 
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "2300:2300"
