- name: 기본적으로 설치되어야 하는 yum package install
  become: yes
  become_user: root
  become_method: sudo
  yum:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - unzip
      - jq
      - vim
      - git

- name: node to node RSA 4096 settings
  copy:
    src: "secrets/{{ item.src }}"
    dest: "/home/ec2-user/.ssh/{{ item.dest }}"
    mode: 0600
  with_items:
    - { src: 'pickstudio_id_rsa', dest: 'id_rsa' }
    - { src: 'pickstudio_id_rsa.pub', dest: 'id_rsa.pub' }

- name: id_rsa.pub키 authorized_keys 등록
  become: yes
  become_user: root
  become_method: sudo
  shell: |
    cat /home/ec2-user/.ssh/id_rsa.pub >> /home/ec2-user/.ssh/authorized_keys

- name: 시작시 실행항 initialize script 복사 - init_ssh
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: init_ssh.sh
    dest: /root/init_ssh.sh
    owner: root
    group: root
    mode: 0700
