#cloud-config
timezone: Asia/Seoul

runcmd:
  # kernel tuning
  - |
    echo "kernel tuning" >> /var/run/cloud-init/log
    swapoff -a
    sysctl -w vm.max_map_count=262144
    ulimit -u 65535

  - |
    echo "docker-compose up" >> /var/run/cloud-init/log
    chown root:root /services/config/metricbeat/metricbeat.yml
    export ACCOUNT=$(cat /run/cloud-init/instance-data.json | jq -rM '.ds.dynamic["instance-identity"].document.accountId')
    aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin "$ACCOUNT.dkr.ecr.ap-northeast-2.amazonaws.com"
    docker-compose -f /services/app/docker-compose.yml up -d

  - |
    authorizedKeyFile='/home/ec2-user/.ssh/authorized_keys'
    IFS=$"\,"
    accounts=($github_accounts)
    IFS=$' '

    for account in $accounts; do
      echo $account
      curl -s https://github.com/$account.keys >> $authorizedKeyFile
    done

    chown -R ec2-user:ec2-user $authorizedKeyFile
    chmod 600 $authorizedKeyFile

write_files:
  # kernel tuning limit
  - path: /etc/security/limits.conf
    content: |
      *       soft    nofile  65536
      *       hard    nofile  65536
      root    soft    nofile  65536
      root    hard    nofile  65536
      elasticsearch  -  nofile  65535

      *       soft    nproc  65536
      *       hard    nproc  65536

      *       soft    memlock unlimited
      *       hard    memlock unlimited
    append: true
