version: "3"

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12345:12345" # agent
      - "12346:12346" # grpc
      - "8500:8500" # consul
    environment:
      CLUSTER_NAME: pickstudio
      NAMESPACE_NAME: grafana

      CONFIG_DISCOVERY_YAML: /etc/agent/ecs_file_sd.yml

      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

      REMOTE_WRITE_PROM_PUSH_DSN: ${REMOTE_WRITE_PROM_PUSH_DSN}
      REMOTE_WRITE_PROM_PUSH_DSN_USERNAME: ${REMOTE_WRITE_PROM_PUSH_DSN_USERNAME}
      REMOTE_WRITE_PROM_PUSH_DSN_PASSWORD: ${REMOTE_WRITE_PROM_PUSH_DSN_PASSWORD}

      REMOTE_WRITE_TEMPO_PUSH_DSN: ${REMOTE_WRITE_TEMPO_PUSH_DSN}
      REMOTE_WRITE_TEMPO_PUSH_USERNAME: ${REMOTE_WRITE_TEMPO_PUSH_USERNAME}
      REMOTE_WRITE_TEMPO_PUSH_PASSWORD: ${REMOTE_WRITE_TEMPO_PUSH_PASSWORD}

      REMOTE_WRITE_LOKI_PUSH_DSN: ${REMOTE_WRITE_LOKI_PUSH_DSN}
      REMOTE_WRITE_LOKI_PUSH_USERNAME: ${REMOTE_WRITE_LOKI_PUSH_USERNAME}
      REMOTE_WRITE_LOKI_PUSH_PASSWORD: ${REMOTE_WRITE_LOKI_PUSH_PASSWORD}
