- name: 파일 오픈 관련 내용 추가 관련 내용 추가(1)
  become: yes
  become_user: root
  become_method: sudo
  shell: 'echo "DefaultLimitNPROC=65536" >> /etc/systemd/system.conf'

- name: 파일 오픈 관련 내용 추가 관련 내용 추가(2)
  become: yes
  become_user: root
  become_method: sudo
  shell: 'echo "DefaultLimitNOFILE=65536" >> /etc/systemd/system.conf'
